namespace MooseEngine.Core
{
    public enum InputOptions
    {
        Zero,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        UpAction,
        DownAction,
        LeftAction,
        RightAction,
        PickUpItem,
        PickUpItemIndex,
        ItemDropIndex,
        InpectInventory,
        Interact,
        Tab,
        Idle,
        QuitToMenu,
        QuitGame,
        RestartGame,
        AutoEquip,
        All
    }
}
