namespace MooseEngine.Core
{
    public enum InputOptions : int
    {
        Zero,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        UpAction,
        DownAction,
        LeftAction,
        RightAction,
        ItemPickUp,
        ItemDrop,
        Interact,
        Tab,
        Idle,
        QuitToMenu,
        QuitGame,
        RestartGame,
        AutoEquip
    }
}
